name: Scrape Anime XML

on:
  workflow_dispatch:
    inputs:
      aid:
        description: 'Anime ID (AID) to fetch'
        required: true
        default: '1'

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install beautifulsoup4 lxml requests

    - name: Create output directory
      run: mkdir -p output

    - name: Run the scraper
      run: python scrape_anime.py ${{ github.event.inputs.aid }} output

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: anime-episodes-json
        path: output/
